name: learn-github-actions
run-name: ${{ github.actor}} is learning Actions
on: [push]
jobs:
  check-dart-version:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2.12.0
    - run: dart -v